---
- name: Install HAProxy and MariaDB client
  apt:
    name:
      - haproxy
      - mariadb-client
    state: present
    update_cache: yes

- name: Ensure HAProxy config directory exists
  file:
    path: /etc/haproxy
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Set HAProxy bind IP
  set_fact:
    haproxy_bind_ip: "192.168.159.139"

- name: Deploy HAProxy configuration
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'
  notify: Restart HAProxy

- name: Ensure HAProxy is enabled and started
  systemd:
    name: haproxy
    enabled: true
    state: started