---
- name: Create Zabbix Database
  community.mysql.mysql_db:
    name: zabbix
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create Zabbix User with Privileges
  community.mysql.mysql_user:
    name: zabbix
    password: MyPassword!@#
    priv: "zabbix.*:ALL"
    host: "%"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
