---
- name: Create Zabbix database and user (ONLY after Galera cluster is ready)
  hosts: db1
  become: true
  collections:
    - community.mysql
  tasks:

    - name: Create Zabbix Database
      community.mysql.mysql_db:
        name: zabbix
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Create Zabbix User with full access
      community.mysql.mysql_user:
        name: zabbix
        password: MyPassword!@#
        priv: "zabbix.*:ALL"
        host: "%"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock



# - name: Create Zabbix database and user (AFTER cluster is up)
#   hosts: db1
#   become: true
#   collections:
#     - community.mysql
#   tasks:
#     - import_tasks: roles/database/tasks/zabbix-db.yml
